[workspace]
members = [
  "src3_mint_burn/single_asset",
  "src3_mint_burn/multi_asset",
  "src5-ownership/initialized_example",
  "src5-ownership/uninitialized_example",
  "src6-vault/multi_asset_vault",
  "src6-vault/single_asset_single_sub_vault",
  "src6-vault/single_asset_vault",
  "src7-metadata/single_asset",
  "src7-metadata/multi_asset",
  "src11-security-information/hardcoded-information",
  "src11-security-information/variable-information",
  "src12-contract-factory/with_configurables",
  "src12-contract-factory/without_configurables",
  "src14-simple-proxy/owned",
  "src14-simple-proxy/minimal",
  "src20-native-asset/single_asset",
  "src20-native-asset/multi_asset",
]
